version: "3.3"

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80" # HTTP for CMS and redirects
            - "443:443" # HTTPS for Next.js
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./wp:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - wordpress
            - nextjs
        restart: always
        healthcheck:
            test: ["CMD", "nginx", "-t"]
            interval: 30s
            timeout: 10s
            retries: 3

    wordpress:
        image: wordpress:php8.1-fpm
        container_name: wordpress
        volumes:
            - ./wp:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_HOME','http://${CMS_DOMAIN}');
                define('WP_SITEURL','http://${CMS_DOMAIN}');
        depends_on:
            - db
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "php-fpm -t || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3

    db:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 3

    nextjs:
        container_name: nextjs
        build:
            context: ./nextjs-app
            dockerfile: Dockerfile
            args:
                NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-secret-key}
                NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
                NEXT_PUBLIC_CMS: ${NEXT_PUBLIC_CMS:-https://cms.ziohair.vn}
                NEXT_PUBLIC_API: ${NEXT_PUBLIC_API:-/wp-json/wp/v2}
                NEXT_PUBLIC_AMB_API: ${NEXT_PUBLIC_AMB_API:-/wp-json/amb/v1}
                NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN:-https://ziohair.vn}
                NEXT_PUBLIC_LANDING_DOMAIN: ${NEXT_PUBLIC_LANDING_DOMAIN:-https://ziohair.vn}
                NEXT_PUBLIC_STORE_DOMAIN: ${NEXT_PUBLIC_STORE_DOMAIN:-https://sanpham.ziohair.vn}
                NEXT_PUBLIC_BOOKING_DOMAIN: ${NEXT_PUBLIC_BOOKING_DOMAIN:-https://booking.ziohair.vn}
                NEXT_PUBLIC_LANDING_HOST_NAME: ${NEXT_PUBLIC_LANDING_HOST_NAME:-ziohair.vn}
                NEXT_PUBLIC_STORE_HOST_NAME: ${NEXT_PUBLIC_STORE_HOST_NAME:-sanpham.ziohair.vn}
                NEXT_PUBLIC_BOOKING_HOST_NAME: ${NEXT_PUBLIC_BOOKING_HOST_NAME:-booking.ziohair.vn}
                NEXT_PUBLIC_CMS_HOST_NAME: ${NEXT_PUBLIC_CMS_HOST_NAME:-cms.ziohair.vn}
                NEXT_PUBLIC_ROBOTS: ${NEXT_PUBLIC_ROBOTS:-noindex,nofollow}
                NEXT_PUBLIC_API_CF7: ${NEXT_PUBLIC_API_CF7:-/wp-json/contact-form-7/v1}
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key}
            - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
            - NEXT_PUBLIC_CMS=${NEXT_PUBLIC_CMS:-https://cms.ziohair.vn}
            - NEXT_PUBLIC_API=${NEXT_PUBLIC_API:-/wp-json/wp/v2}
            - NEXT_PUBLIC_AMB_API=${NEXT_PUBLIC_AMB_API:-/wp-json/amb/v1}
            - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN:-https://ziohair.vn}
            - NEXT_PUBLIC_LANDING_DOMAIN=${NEXT_PUBLIC_LANDING_DOMAIN:-https://ziohair.vn}
            - NEXT_PUBLIC_STORE_DOMAIN=${NEXT_PUBLIC_STORE_DOMAIN:-https://sanpham.ziohair.vn}
            - NEXT_PUBLIC_BOOKING_DOMAIN=${NEXT_PUBLIC_BOOKING_DOMAIN:-https://booking.ziohair.vn}
            - NEXT_PUBLIC_LANDING_HOST_NAME=${NEXT_PUBLIC_LANDING_HOST_NAME:-ziohair.vn}
            - NEXT_PUBLIC_STORE_HOST_NAME=${NEXT_PUBLIC_STORE_HOST_NAME:-sanpham.ziohair.vn}
            - NEXT_PUBLIC_BOOKING_HOST_NAME=${NEXT_PUBLIC_BOOKING_HOST_NAME:-booking.ziohair.vn}
            - NEXT_PUBLIC_CMS_HOST_NAME=${NEXT_PUBLIC_CMS_HOST_NAME:-cms.ziohair.vn}
            - NEXT_PUBLIC_ROBOTS=${NEXT_PUBLIC_ROBOTS:-noindex,nofollow}
            - NEXT_PUBLIC_API_CF7=${NEXT_PUBLIC_API_CF7:-/wp-json/contact-form-7/v1}
        restart: always
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:3000/api/health || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    db_data:
