name: Deploy NextJS to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Copy SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Add VPS to known_hosts
              run: |
                  ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy NextJS
              run: |
                  ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
                    set -e
                    cd ${{ secrets.PROJECT_PATH }}
                    rm -rf nextjs-app
                    git clone $GITHUB_SERVER_URL/${GITHUB_REPOSITORY}.git nextjs-app
                    docker-compose build nextjs
                    docker-compose up -d nextjs
                  "
